# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245a00080f561f103a54f8ac217a14e4ccdbbd9c5602a00bbf80ba5c565a9c67b505373ffb01b7a9226f4bfab0478e913797b0480e41fc17c12611d70455eeba

test:
  secret_key_base: daa3d3b6ed26e4ab3dac7a58dd9eeda41c3bc30747a037f9eea0a4c485f515fbc46d77a4f0da50b48d409e50129c20e70ecc6e63978e501fe72c73da96cd9489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
